<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="L510095" ignored="0" name="Home page Test - Chrome" tests="7" failures="1" timestamp="24 Jun 2021 07:50:18 GMT" time="42.116" errors="0">
  <testcase name="homePageHeaderTest" time="5.433" classname="com.qa.qs.tests.HomePageTest"/>
  <testcase name="homePageTitleTest" time="0.024" classname="com.qa.qs.tests.HomePageTest"/>
  <testcase name="userAccountNameTest" time="5.945" classname="com.qa.qs.tests.HomePageTest">
    <failure type="java.lang.AssertionError" message="expected [DL] but found [SH13]">
      <![CDATA[java.lang.AssertionError: expected [DL] but found [SH13]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.qa.qs.tests.HomePageTest.userAccountNameTest(HomePageTest.java:60)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- userAccountNameTest -->
  <testcase name="iconHomeExistsTest" time="2.307" classname="com.qa.qs.tests.HomePageTest"/>
  <testcase name="iconMenuExistsTest" time="2.97" classname="com.qa.qs.tests.HomePageTest"/>
  <testcase name="iconHelpExistsTest" time="2.422" classname="com.qa.qs.tests.HomePageTest"/>
  <testcase name="iconAcountExistsTest" time="2.778" classname="com.qa.qs.tests.HomePageTest"/>
</testsuite> <!-- Home page Test - Chrome -->
